addAssignees: author

addReviewers: true

numberOfReviewers: 5

reviewers:
  - shirosweets
  - AgustinMDominguez
  - diofanto33
  - IvanRenison
  - gpratoe
  - ErnestoCarrizo
  - achaval-tomas
  - santiagofada
  - Lautron
  - FranAyrolo

runOnDraft: true

filterLabels:
  exclude:
    - wip
