name: 'Dispatch to Repository Action'
on:
  push:
    branches:
      - main
  # workflow_dispatch

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repositories: [
          'FAMAF-resources/Template-repository'
        ]
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.FRM_APP_ID }}
          private-key: ${{ secrets.FRM_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Debug Token Scope
        run: |
          echo "Listing repositories accessible by this token:"
          curl -X GET -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/installation/repositories | jq '.repositories[].full_name'

      - name: Push to repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ${{ matrix.repositories }}
          event-type: update-submodules-famaf
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "owner/submodule", "branch": "main"}'